package fftadata;

public enum FFTASkillDesc 
{
	FIGHT			("Attack with equipped weapon.", ""),
	FIGHT_L			("Attack with equipped weapon.", ""),
	DRAIN_WEAPON	("Attack with equipped weapon.", ""),
	DRAIN_WEAPON_L	("Attack with equipped weapon.", ""),
	DOUBLE_SWORD	("Attack with both equipped weapons.", ""),
	RETURN_FIRE		("", ""),
	CURE			("Restores HP to units in a small area.", ""),
	CURA			("Restores HP to units in a small area.", ""),
	CURAGA			("Restores HP to units in a small area.", ""),
	ESUNA			("Removes negative status effects from units in a small area.", "Esuna " + CommonDesc.X_ESUNA),
	LIFE			("Revives a fallen unit with 50% HP.", ""),
	FULL_LIFE		("Revives a fallen unit with full HP.", ""),
	AUTO_LIFE		("Grants Auto-Life to a single unit.", StatusEffect.AUTO_LIFE.DESC),
	SHELL			("Grants Shell to units in a small area.", StatusEffect.SHELL.DESC),
	PROTECT			("Grants Protect to units in a small area.", StatusEffect.PROTECT.DESC),
	DISPEL			("Removes certain magical effects from units in a small area.", "Dispel " + CommonDesc.X_DISPEL),
	HOLY			("Deals Holy-elemental damage to units in a small area.", ""),
	BARRIER			("Grants Shell and Protect to a single unit.", CommonDesc.BARRIER),
	JUDGE			("", ""),
	BREAK			("Inflicts Petrify on a single unit.", StatusEffect.PETRIFY.DESC),
	WATER			("Deals Water-elemental damage to units in a small area.", ""),
	AERO			("Deals Wind-elemental damage to units in a small area.", ""),
	DRAIN			("Drains HP from a single unit.", CommonDesc.DRAIN),
	BLIND			("Inflicts Darkness on a single unit.", StatusEffect.DARKNESS.DESC),
	RAISE			("Restores HP to units in a small area and revives fallen units with 50% HP.", ""),
	GIGA_FLARE		("Deals magical damage to units in a small area.", ""),
	BIO				("Deals damage and inflicts Poison in a small area.", StatusEffect.POISON.DESC),
	ULTIMA_BLOW		("Deals triple physical damage to a single unit.", ""),
	FIRE			("Deals Fire-elemental damage to units in a small area.", ""),
	FIRA			("Deals Fire-elemental damage to units in a small area.", ""),
	FIRAGA			("Deals Fire-elemental damage to units in a small area.", ""),
	THUNDER			("Deals Lightning-elemental damage to units in a small area.", ""),
	THUNDARA		("Deals Lightning-elemental damage to units in a small area.", ""),
	THUNDAGA		("Deals Lightning-elemental damage to units in a small area.", ""),
	BLIZZARD		("Deals Ice-elemental damage to units in a small area.", ""),
	BLIZZARA		("Deals Ice-elemental damage to units in a small area.", ""),
	BLIZZAGA		("Deals Ice-elemental damage to units in a small area.", ""),
	SLEEP			("Inflicts Sleep to units in a small area.", StatusEffect.SLEEP.DESC),
	DOUBLECAST		("Casts two spells of the user's choice in a row.", "All White, Red, Spirit, and Summon Magic abilities are eligible for Doublecast."),
	QUICKEN			("Grants Quick to a single unit.", StatusEffect.QUICK.DESC),
	SLOW			("Inflicts Slow to units in a small area.", StatusEffect.SLOW.DESC),
	REFLECT			("Grants Reflect to a single unit.", StatusEffect.REFLECT.DESC),
	STOP			("Inflicts Stop to units in a small area.", StatusEffect.STOP.DESC),
	QUARTER			("Cuts a single unit's HP by 25% of its current value.", ""),
	DEMI			("Cuts a single unit's HP by 50% of its current value.", ""),
	SILENCE			("Inflicts Silence to units in a small area.", StatusEffect.SILENCE.DESC),
	HASTE			("Grants Haste to a single unit.", StatusEffect.HASTE.DESC),
	PROMINENCE		("Deals Fire-elemental damage to all enemy units.", ""),
	TEMPEST			("Deals Lightning-elemental damage to all enemy units.", ""),
	FREEZEBLINK		("Deals Ice-elemental damage to all enemy units.", ""),
	STAR_CROSS		("Deals Holy-elemental damage to all enemy units.", ""),
	STARDUST		("Deals magical damage to all enemy units.", ""),
	DELUGE			("Deals Water-elemental damage to all enemy units.", ""),
	SOIL_EVIDENCE	("Deals Earth-elemental damage to all enemy units.", ""),
	WILD_TORNADO	("Deals Wind-elemental damage to all enemy units.", ""),
	FIRE_WHIP		("Deals Fire-elemental damage and inflicts Disable on a single unit.", StatusEffect.DISABLE.DESC),
	EARTH_HEAL		("Restores HP to a single unit.", ""),
	WHITE_FLAME		("Restores HP to units in a small area.", ""),
	SHINING_AIR		("Deals Wind-elemental damage and inflicts Darkness on a single unit.", StatusEffect.DARKNESS.DESC),
	EVIL_GAZE		("Deals Dark-elemental damage and inflicts Confuse on a single unit.", StatusEffect.CONFUSE.DESC),
	HEAVY_DUST		("Deals Earth-elemental damage and inflicts Immobilize on a single unit.", StatusEffect.IMMOBILIZE.DESC),
	SLIPRAIN		("Deals Water-elemental damage and inflicts Slow on a single unit.", StatusEffect.SLOW.DESC),
	ELEMENTALSHIFT	("", ""),
	ASTRA			("Grants Astra to units in a small area.", StatusEffect.ASTRA.DESC),
	RASP			("Deals damage to units' MP in a small area.", ""),
	DEATH			("Inflicts Death on a single unit.", ""),
	METEOR			("Deals damage to units in a small area.", ""),
	FLARE			("Deals damage to a single unit.", ""),
	POISON			("Inflicts Poison on units in a small area.", StatusEffect.POISON.DESC),
	TOAD			("Inflicts Frog on a single unit.", StatusEffect.FROG.DESC),
	UNICORN			("Restores HP and removes negative status effects from units in a large area.", "Unicorn " + CommonDesc.X_ESUNA),
	IFRIT			("Deals Fire-elemental damage to units in a large area.", ""),
	RAMUH			("Deals Lightning-elemental damage to units in a large area.", ""),
	SHIVA			("Deals Ice-elemental damage to units in a large area.", ""),
	KIRIN			("Grants Regen to units in a large area.", StatusEffect.REGEN.DESC),
	CARBUNCLE		("Grants Reflect to units in a large area.", StatusEffect.REFLECT.DESC),
	PHOENIX			("Revives units in a large area with full HP.", ""),
	MADEEN			("Deals Holy-elemental damage to units in a large area.", ""),
	FIRST_AID		("Restores the user's HP and removes negative status effects.", "First Aid " + CommonDesc.X_ESUNA),
	POWERBREAK		("Inflicts Weapon ATK Down on a single unit.", StatusEffect.WATK_DOWN.DESC),
	MINDBREAK		("Inflicts Magic POW Down on a single unit.", StatusEffect.MPOW_DOWN.DESC),
	MAGICBREAK		("Deals weapon damage to a single unit's MP.", ""),
	SPEEDBREAK		("Inflicts Speed Down on a single unit.", StatusEffect.SPEED_DOWN.DESC),
	MUG				("", "Though Mug's gil-stealing effect is not available in Swords in Cyril, the ability may still be used to inflict normal damage."),
	PROVOKE			("Inflicts Berserk on a single unit.", StatusEffect.BERSERK.DESC),
	BODY_SLAM		("Deals physical damage to an adjacent unit, but damages the user.", CommonDesc.RECOIL),
	GREASED_BOLT	("Deals weapon damage to a single unit, ignoring their R-Ability.", CommonDesc.IGNORE_REACTION),
	DOWNSIZE		("Cuts a single unit's HP by 1/2 of its current value.", ""),
	NURSE			("Restores HP in a small area centered on the user and removes negative status effects.", "Nurse " + CommonDesc.X_ESUNA),
	COVER			("Protects an ally from damage until the user's next turn.", "The user will temporarily switch places with their target whenever the target would take damage, and receive all effects of the attack in their stead."),
	SUBDUE			("Deals insignificant damage to a single unit.", "Subdue randomly deals between 2 and 12 damage."),
	PARLEY			("", ""),
	SAINT_CROSS		("Deals Holy-elemental damage to all adjacent units.", ""),
	HOLY_BLADE		("Deals 2x weapon damage to a single unit.", ""),
	DEFENSE			("Grants Defense to the user until their next turn.", StatusEffect.DEFENSE.DESC),
	DROP_WEAPON		("Removes one weapon from a single unit.", CommonDesc.REMOVE_WEAPON),
	TREMOR			("", ""),
	HIBERNATE		("", ""),
	MOW_DOWN		("", ""),
	AURA			("Grants Regen and Auto-Life to the user.", ""),
	EXPERT_GUARD	("Negates all damage to the user until their next turn.", "Most attacks will automatically hit the user during this duration."),
	MELTDOWN		("Kills the user to damage all surrounding units.", "The damage dealt is equal to the user's current HP."),
	WHIRLWIND		("Deals physical damage to all adjacent units.", ""),
	EARTH_RENDER	("Deals physical damage to units in a line in front of the user.", ""),
	CHAKRA			("Restores HP to the user and removes negative status effects", "Chakra " + CommonDesc.X_ESUNA),
	REVIVE			("Revives an adjacent unit with 25% of their max HP.", ""),
	HOLY_SIGN		("Removes certain magical effects from an adjacent unit.", "Holy Sign " + CommonDesc.X_DISPEL),
	AIR_RENDER		("Deals physical damage to a unit from a distance.", ""), 
	FAR_FIST		("Deals physical damage to units in a small area.", ""),
	AIR_BLAST		("Deals Wind-elemental damage to units in a cone-shaped area.", ""),
	BACKDRAFT		("Deals physical damage to an adjacent unit, but damages the user.", CommonDesc.RECOIL),
	RUSH			("", ""),
	WILD_SWING		("Deals weapon damage to all adjacent units.", ""),
	BEATDOWN		("Deals 2x weapon damage to a single unit, but at 0.5x accuracy.", ""),
	BLITZ			("Deals 0.5x weapon damage to a single unit, but at 2x accuracy.", ""),
	FIRE_SWORD		("Deals Fire-elemental damage to an adjacent unit.", ""),
	BOLT_SWORD		("Deals Lightning-elemental damage to an adjacent unit.", ""),
	ICE_SWORD		("Deals Ice-elemental damage to an adjacent unit.", ""),
	ULTIMA_SWORD	("Deals 3x weapon damage to a single unit.", ""),
	WARCRY			("Inflicts Speed Down on all adjacent units.", StatusEffect.SPEED_DOWN.DESC),
	CHEER			("Increases the damage of the user's next attack.", "Cheer " + CommonDesc.BOOST),
	SOUL_SPHERE		("Deals weapon damage to units' MP in a small area.", ""),
	LIFEBREAK		("Deals damage to an adjacent unit according to the difference between the user's max and current HP.", ""), 
	JUMP			("Deals damage to a unit from a distance.", "Jump can only be used with a spear equipped."),
	LANCET			("Drains HP from an adjacent unit.", CommonDesc.DRAIN),
	FIRE_BREATH		("Deals Fire-elemental damage to units in a cone-shaped area.", ""),
	BOLT_BREATH		("Deals Lightning-elemental damage to units a cone-shaped area.", ""),
	ICE_BREATH		("Deals Ice-elemental damage to units in a cone-shaped area.", ""),
	WYRMKILLER		("Deals weapon damage to a single target.", "Though Wyrmkiller's bonus damage to Dragons is not available in Swords in Cyril, the ability may still be used to inflict normal damage."),
	BANGAA_CRY		("Deals physical damage to units in a cone-shaped area.", ""),
	MOG_ATTACK		("Deals weapon damage and pushes back a single unit.", ""),
	MOG_GUARD		("Grants Defense to the user until their next turn.", StatusEffect.DEFENSE.DESC),
	MOG_LANCE		("Deals weapon damage to a unit from a distance.", ""),
	MOG_RUSH		("Deals double damage to a single unit, but at 0.5x accuracy.", ""),
	MOG_SHIELD		("Grants Astra to the single unit.", StatusEffect.ASTRA.DESC),
	MOG_AID			("Restores HP to the user and removes negative status effects.", "Mog Aid " + CommonDesc.X_ESUNA),
	ULTIMA_CHARGE	("Deals 3x weapon damage to a single unit.", ""),
	SWARMSTRIKE		("Deals 0.5x weapon damage and inflicts Poison on a single unit.", StatusEffect.POISON.DESC),
	SHADOWSTICK		("Inflicts Speed Down on a single unit.", StatusEffect.SPEED_DOWN.DESC),
	CHECKMATE		("Inflicts Doom on a single unit.", StatusEffect.DOOM.DESC),
	FEATHERBLOW		("Deals 0.5x weapon damage to a unit, but at 2x accuracy.", ""),
	SWALLOWTAIL		("Deals weapon damage to all adjacent units.", ""),
	MANASTRIKE		("Deals weapon damage to a single unit's MP.", ""),
	PIERCETHROUGH	("Deals weapon damage in two tiles in front of the user.", ""),
	NIGHTHAWK		("Deals weapon damage to a unit from a distance.", ""),
	THROW			("", ""),
	WOOD_VEIL		("Deals magical damage and inflicts Immobilize on a single unit.", StatusEffect.IMMOBILIZE.DESC),
	FIRE_VEIL		("Deals Fire-elemental damage and inflicts Confuse on a single unit.", StatusEffect.CONFUSE.DESC),
	EARTH_VEIL		("Deals Earth-elemental damage and inflicts Slow and Delay on a single unit.", StatusEffect.SLOW.DESC + "<br><br>" + CommonDesc.DELAY),
	METAL_VEIL		("Deals magical damage and inflicts Darkness on a single unit.", StatusEffect.DARKNESS.DESC),
	WATER_VEIL		("Inflicts Water-elemental damage and inflicts Silence on a single unit.", StatusEffect.SILENCE.DESC),
	UNSPELL			("Removes certain magical effects from an adjacent unit.", "Unspell " + CommonDesc.X_DISPEL),
	OBLIVION		("Inflicts Addle on an adjacent unit.", StatusEffect.ADDLE.DESC),
	SHADOWBIND		("Inflicts Stop on an adjacent unit.", StatusEffect.STOP.DESC),
	LAST_BREATH		("Inflicts Death on an adjacent unit.", ""),
	APHONIA			("Inflicts Silence on an adjacent unit.", StatusEffect.SILENCE.DESC),
	NIGHTMARE		("Inflicts Doom and Sleep on a single unit.", StatusEffect.DOOM.DESC + "<br><br>" + StatusEffect.SLEEP.DESC),
	AGUE			("Inflicts Slow on a single unit.", StatusEffect.SLOW.DESC),
	ROCKSEAL		("Inflicts Petrify on a single unit.", StatusEffect.PETRIFY.DESC),
	ULTIMA_MASHER	("Deals 3x weapon damage to a single unit.", ""),
	STEAL_ARMOR		("Removes an adjacent enemy's armor.", CommonDesc.ENEMY_ONLY),
	STEAL_SHIELD	("Removes an adjacent enemy's shield.", CommonDesc.ENEMY_ONLY),
	STEAL_ACCESS	("Removes one accessory from an adjacent enemy.", CommonDesc.REMOVE_ACCESS + "<br><br>" + CommonDesc.ENEMY_ONLY),
	STEAL_HELM		("Removes an adjacent enemy's headgear.", CommonDesc.ENEMY_ONLY),
	STEAL_WEAPON	("Removes one weapon from an adjacent enemy.", CommonDesc.REMOVE_WEAPON + "<br><br>" + CommonDesc.ENEMY_ONLY),
	STEAL_JP		("", ""),
	STEAL_ABILITY	("", ""),
	BOOST			("Grants Boost to the user.", "Boost " + CommonDesc.BOOST),
	AIM_LEGS		("Inflicts Immobilize on a single unit.", StatusEffect.IMMOBILIZE.DESC),
	AIM_ARM			("Inflicts Disable on a single unit.", StatusEffect.DISABLE.DESC),
	CUPID			("Inflicts Charm on a single enemy.", CommonDesc.ENEMY_ONLY),
	TAKE_AIM		("Inflicts 0.5x weapon damage on a single unit, but never misses.", ""),
	FASTER			("Inflicts weapon damage on a single unit, ignoring their R-Ability.", CommonDesc.IGNORE_REACTION),
	BLACDeathUT		("Inflicts Darkness on a single unit.", StatusEffect.DARKNESS.DESC),	
	SONIC_BOOM		("Inflicts weapon damage to units in a small area.", ""),
	ADVICE			("Grants Advice to a single unit.", StatusEffect.ADVICE.DESC),
	AIM_VITALS		("Inflicts a random status effect on a single unit.", "Aim: Vitals has an 11/101 chance of inflicting Berserk, 25/101 of Disable, 35/101 of Blind, 25/101 of Immobilize, and 5/101 of reducing the target's HP to 1."),
	HUNTING			("", ""),
	ADDLE			("Inflicts Addle on a single unit.", StatusEffect.ADDLE.DESC),
	ULTIMA_SHOT		("Deals 3x weapon damage to a single unit.", ""),
	SIDEWINDER		("Deals weapon damage to a single unit.", "Though Sidewinder's bonus damage to monsters is not available in Swords in Cyril, the ability may still be used to inflict normal damage."),
	GOBLIN			("Bestows the abilities of a Goblin.", "Unit gains Goblin Punch, Magic Hammer, and Mutilate, at the expense of their primary and secondary abilities. " + CommonDesc.X_MORPH),
	FLAN			("Bestows the abilities of a Flan.", "Unit gains Acid and all Black Magic, at the expense of their primary and secondary abilities. " + CommonDesc.X_MORPH),
	BOMB			("Bestows the abilities of a Bomb.", "Unit gains Blowup, Flame Attack, and Chill, at the expense of their primary and secondary abilities. " + CommonDesc.X_MORPH),
	DRAGON			("Bestows the abilities of a Dragon.", "Unit gains Fire Breath, Lightning Breath, Ice Breath, Mighty Guard, Guard-Off, and Dragon Force, at the expense of their primary and secondary abilities. " + CommonDesc.X_MORPH),
	LAMIA			("Bestows the abilities of a Lamia.", "Unit gains Night, Twister, Hand Slap, Poison Frog, and Kiss, at the expense of their primary and secondary abilities. " + CommonDesc.X_MORPH),
	BUG				("Bestows the abilities of a Bug.", "Unit gains LV3 Def-Less, Sandstorm, LV5 Death, and Suffocate, at the expense of their primary and secondary abilities. " + CommonDesc.X_MORPH),
	PANTHER			("Bestows the abilities of a Panther.", "Unit gains Poison Claw, Hastebreak, Rend, and Blaster, at the expense of their primary and secondary abilities. " + CommonDesc.X_MORPH),
	MALBORO			("Bestows the abilities of a Malboro.", "Unit gains Bad Breath, Goo, and Soundwave, at the expense of their primary and secondary abilities. " + CommonDesc.X_MORPH),
	FLOATEYE		("Bestows the abilities of a Floateye.", "Unit gains Stare, Devil Gaze, Roulette, and Circle, at the expense of their primary and secondary abilities. " + CommonDesc.X_MORPH),
	HURL			("", ""),
	RING			("Inflicts Stop on a single unit.", StatusEffect.STOP.DESC),
	FIREBOMB		("Deals Fire-elemental damage and inflicts Berserk on a single unit.", StatusEffect.BERSERK.DESC),
	BALL			("Inflicts Confuse on a single unit.", StatusEffect.CONFUSE.DESC),
	DAGGER			("Deals physical damage and inflicts Disable on a single unit.", StatusEffect.DISABLE.DESC),		
	SMILE			("Immediately grants an extra turn to a single unit", StatusEffect.QUICK.DESC),
	GIL_TOSS		("Deals 30 damage to a single unit.", "Gil Toss can be used arbitrarily many times with no cost."),
	BESO_TOXICO		("Deals weapon damage and inflicts Poison on a single unit.", StatusEffect.POISON.DESC),
	DEATH_SICKLE	("Inflicts Doom on a single unit.", StatusEffect.DOOM.DESC),
	DOOM_ARCHER		("", ""),
	DOUBLESHOT		("Deals 0.5x weapon damage to a single unit, twice.", ""),
	AIM_ARMOR		("Removes a single unit's armor.", ""),
	AIM_WEAPON		("Removes one weapon from a single unit.", CommonDesc.REMOVE_WEAPON),
	SHEEP_COUNT		("Inflicts Sleep on units in a small area.", StatusEffect.SLEEP.DESC),
	HUNDY_WOOL		("Grants Shell and Protect to the user.", CommonDesc.BARRIER),
	CUISINE			("Completely restores an adjacent unit's HP.", ""),
	TAIL_WAG		("Inflicts Charm on an adjacent enemy.", StatusEffect.CHARM.DESC + "<br><br>" + CommonDesc.ENEMY_ONLY),
	CHOCOBO_RUSH	("Deals physical damage to all units in a line in front of and behind the user.", ""),
	FROGSONG		("Inflicts Frog on a single unit.", StatusEffect.FROG.DESC),
	FRIEND			("Casts a random Summon Magic ability.", "Friend may cast any of Unicorn, Ifrit, Ramuh, Shiva, Kirin, Carbuncle, Phoenix, or Madeen, with equal probability."),
	CATNIP			("Inflicts Berserk on a single unit.", StatusEffect.BERSERK.DESC),
	FIRESHOT		("Inflicts Fire-elemental weapon damage on a single unit.", ""),
	BOLTSHOT		("Inflicts Lightning-elemental weapon damage on a single unit.", ""),
	ICESHOT			("Inflicts Ice-elemental weapon damage on a single unit.", ""),
	CONFUSHOT		("Deals weapon damage and inflicts Confuse on a single unit.", StatusEffect.CONFUSE.DESC),
	CHARMSHOT		("Deals weapon damage and inflicts Charm on a single unit.", StatusEffect.CHARM.DESC),
	BLINDSHOT		("Deals weapon damage and inflicts Darkness on a single unit.", StatusEffect.DARKNESS.DESC),
	SILENSHOT		("Deals weapon damage and inflicts Silence on a single unit.", StatusEffect.SILENCE.DESC),
	STOPSHOT		("Deals weapon damage and inflicts Stop on a single unit.", StatusEffect.STOP.DESC),
	RED_SPRING		("", ""),
	BLUE_SCREW		("", ""),
	GREEN_GEAR		("", ""),
	SILVER_DISC		("", ""),
	GOLD_BATTERY	("", ""),
	BLACK_INGOT		("", ""),
	CHROMA_GEM		("", ""),
	YELLOW_SPRING	("", ""),
	POTION			("Restores 25 HP to an adjacent unit.", ""),
	HI_POTION		("Restores 50 HP to an adjacent unit.", ""),
	X_POTION		("Restores 150 HP to an adjacent unit.", ""),
	ETHER			("Restores 80 MP to an adjacent unit.", ""),
	ELIXIR			("Completely restores HP and MP to an adjacent unit.", ""),
	PHOENIX_DOWN	("Revives a fallen unit with 25% HP.", ""),
	ECHO_SCREEN		("Removes Silence from an adjacent unit.", ""),
	MAIDEN_KISS		("Removes Frog from an adjacent unit.", ""),
	SOFT			("Removes Petrify from an adjacent unit.", ""),
	ANTIDOTE		("Removes Poison from an adjacent unit.", ""),
	EYE_DROPS		("Removes Darkness from an adjacent unit.", ""),
	BANDAGE			("Removes Immobilize and Disable from an adjacent unit.", ""),
	CUREALL			("Removes a variety of status effects from an adjacent unit.", "Cureall removes Petrify, Frog, Poison, Blind, Conceal, Sleep, Silence, and Confusion."),
	DRAW_WEAPON		("", ""),
	GOBLIN_PUNCH	("Deals highly variable physical damage to an adjacent unit.", "Goblin Punch may deal anywhere between 50% and 150% of its predicted damage."),
	MAGIC_HAMMER	("Deals magical damage to a single target's MP.", ""),
	MUTILATE		("Drains a random portion of an adjacent unit's HP.", "Mutilate drains either 25%, 50%, or 75% of the target's current HP, with equal probability."),
	ACID			("Randomly inflicts either Slow, Stop, Immobilize, or Disable on a single unit.", "Acid has an equal chance of applying each status effect."),
//	SACRIFICE		("",
//					 ""),
	BLOWUP			("Deals Fire-elemental damage to all adjacent units, but kills the user.", ""),
	FLAME_ATTACK	("Deals Fire-elemental damage to a single unit.", ""),
	CHILL			("Deals Ice-elemental damage to units in a small area centered on the user, and never misses.", ""),
	MIGHTY_GUARD	("Grants Weapon DEF Up and Magic RES Up to a single unit.", "Weapon DEF and Magic RES both increase by about 40%. Both effects last indefinitely."),
	GUARD_OFF		("Inflicts Weapon DEF Down and Magic RES Down on a single unit.", CommonDesc.GUARD_OFF),
	DRAGON_FORCE	("Grants Weapon ATK Up, Weapon DEF Up, Magic POW Up, and Magic RES Up to a single unit.", "Weapon ATK and Magic POW increase by about 10% each, while Weapon DEF and Magic RES incrase by about 40%. All four effects last indefinitely."),
	NIGHT			("Inflicts Sleep on all units on the battlefield.", StatusEffect.SLEEP.DESC),
	TWISTER			("Cuts units' HP by 50% in a small area.", ""),
	HAND_SLAP		("Deals physical damage and inflicts Delay on an adjacent unit.", CommonDesc.DELAY),
	POISON_FROG		("Inflicts Poison and Frog on a single unit.", StatusEffect.POISON.DESC + "<br><br>" + StatusEffect.FROG.DESC),
	KISS			("Inflicts Doom and Charm on a single target.", StatusEffect.DOOM.DESC + "<br><br>" + StatusEffect.CHARM.DESC),
	LV3_DEF_LESS	("Inflicts Weapon DEF Down and Magic RES Down on units in a small area whose levels are divisble by 3.", CommonDesc.GUARD_OFF + "<br><br>" + CommonDesc.LEVEL_X),
	SANDSTORM		("Deals Earth-elemental damage and inflicts Darkness on all adjacent units.", ""),
	LV5_DEATH		("Inflicts Death on units in a small area whose level is divisible by 5.", CommonDesc.LEVEL_X),
	SUFFOCATE		("Inflicts Delay on a single unit.", CommonDesc.DELAY),
	MATRA_MAGIC		("Swaps a single unit's HP and MP values.", "HP and MP will cap and their normal maximums."),
	POISON_CLAW		("Deals physical damage and inflicts Poison on a single unit.", StatusEffect.POISON.DESC),
	HASTEBREAK		("Inflicts Stop on a unit with Haste, or Slow on a unit without it.", ""),
	REND			("Deals Physical damage to an adjacent unit.", ""),
	BLASTER			("Inflicts Petrify on a single unit.", StatusEffect.PETRIFY.DESC),
	BAD_BREATH		("Inflicts many status ailments on a single unit.", "Bad Breath attempts to inflict all of the following status conditions at once: Poison, Darkness, Silence, Sleep, Slow, Frog, and Confuse."),
	GOO				("Inflicts Immobilize on an adjacent unit.", StatusEffect.IMMOBILIZE.DESC),
	SOUNDWAVE		("Removes certain magical effects from units in a small area.", "Soundwave removes Auto-Life, Regen, Conceal, Shell, and Protect."),
	STARE			("Inflicts Confuse on units facing the user.", StatusEffect.CONFUSE.DESC + "<br><br>" + CommonDesc.EYE2EYE),
	ROULETTE		("Inflicts Death on a random unit on either side.", "The target is selected from among all living units with equal probability."),
	DEVIL_GAZE		("Inflicts Darkness and Silence on units facing the user.", StatusEffect.DARKNESS.DESC + "<br><br>" + StatusEffect.SILENCE.DESC + "<br><br>" + CommonDesc.EYE2EYE),
	CIRCLE			("Inflicts Weapon ATK Down and Magic POW Down on a single unit.", "Weapon ATK and Magic POW both decrease by about 10%. Both effects last indefinitely."),
	DRAIN_TOUCH		("Drains HP from an adjacent unit.", CommonDesc.DRAIN),
	LVQ_S_FLARE		("Dealls Dark-elemental damage to all units who share the user's level's final digit.", "Targets allies as well as enemies. " + CommonDesc.LEVEL_X),
	WHITE_WIND		("Restores HP equal to the user's current HP to units in a small area.", ""),
	ANGEL_WHISPER	("Restores HP and grants Auto-Life to a single unit.", StatusEffect.AUTO_LIFE.DESC),
	ADRAMMALECH		("Deals physical damage to all enemies.", ""),
	MATEUS			("Deals physical damage to all enemies.", ""),
	ULTIMA			("Deals magical damage to all enemies' MP.", ""),
	EXODUS			("Deals magical damage to all enemies' MP.", ""),
	FAMFRIT			("Deals magical damage to all enemies.", ""),
	OMEGA			("Deals 2x weapon damage to a single unit.", ""),
	ABYSS			("Deals magical damage and inflicts Poison on units in a small area.", StatusEffect.POISON.DESC),
	LIFE_RENDER		("Deals weapon damage and inflicts Doom on a single unit.", StatusEffect.DOOM.DESC),
	HEART_RENDER	("Deals weapon damage to a single unit's MP.", ""),
	RIPCIRCLE		("Deals physical damage to all surrounding units.", ""),
	FURYCIRCLE		("Deals physical damage and pushes back all surrounding units.", ""),
	
	// Unusable abilities
	SENSOR			("No effect.", "This ability is not available in Swords in Cyril."),
	AIM_WALLET		("No effect.", "This ability is not available in Swords in Cyril."),
	EXORCISE		("No effect.", "This ability is not available in Swords in Cyril."),
	CAPTURE			("No effect.", "This ability is not available in Swords in Cyril."),
	OUST			("No effect.", "This ability is not available in Swords in Cyril."),
	CONCEAL			("No effect.", "This ability is not available in Swords in Cyril."),
	STEAL_GIL		("No effect.", "This ability is not available in Swords in Cyril."),
	STEAL_EXP		("No effect.", "This ability is not available in Swords in Cyril."),
	MOG_PEEK		("No effect.", "This ability is not available in Swords in Cyril."),
	WYRMTAMER		("No effect.", "This ability is not available in Swords in Cyril."),
	BURIAL			("No effect.", "This ability is not available in Swords in Cyril."),
	HOLY_WATER		("No effect.", "This ability is not available in Swords in Cyril.");
	
	
	public final String SHORT_DESC, LONG_DESC;
	
	
	
	FFTASkillDesc(String shortDesc, String longDesc)
	{
		SHORT_DESC = shortDesc;
		LONG_DESC = longDesc;
	}
	
	FFTASkillDesc(String shortDesc, CommonDesc commonDesc)
	{
		this(shortDesc, commonDesc.text);
	}
}

enum CommonDesc 
{
	BARRIER			("Shell and Protect increase Magic RES and Weapon DEF (respectively) by about 40% for 3 turns."),
	BOOST			("The user's base Weapon ATK and Magic POW will be increased by about 50% for their next action."),
	DELAY			("Delay resets the target's Counter resets to 0, forestalling their next turn. The sooner the target's turn is, the greater effect Delay will have."),
	DRAIN			("HP restored is equal to damage dealt, capped at the caster's max HP."),
	ENEMY_ONLY		("Cannot be used on allies."),
	EYE2EYE			("This move is 100% accurate if the target is facing the user."),
	GUARD_OFF		("Weapon DEF and Magic RES both decrease by about 30%. Both effects last indefinitely."),
	IGNORE_REACTION	("This ability won't trigger Reaction Abilities like Counter and Damage>MP."),
	LEVEL_X			("This move is 100% accurate if the level condition is satisfied."),
	
	RECOIL			("After damaging the target, the user suffers 25% of the damage dealt as recoil."),
	REMOVE_WEAPON	("The target's right-hand (upper) weapon will always be removed before the left (lower)."),
	REMOVE_ACCESS	("Shoes cannot be stolen."),
	
	X_DISPEL("removes Auto-Life, Regen, Astra, Reflect, Doom, Haste, Slow, Stop, Shell, Protect, Charm, and Addle."),
	X_ESUNA ("removes Petrify, Berserk, Frog, Poison, Darkness, Sleep, Silence, Confuse, Immobilize, and Disable."),
	X_MORPH			("Weapon ATK and Magic POW are increased to 999 for the duration. Ending the transformation does not use up the unit's action.");
	
	String text;
	
	CommonDesc(String text)
	{
		this.text = text;
	}
	
	public String toString()
	{
		return text;
	}
}
