package fftadata;
public enum FFTARace
{
	BANGAA	("Bangaa",
			 new FFTAJob[] 		{FFTAJob.WARRIOR, FFTAJob.DRAGOON, FFTAJob.DEFENDER, FFTAJob.GLADIATOR, FFTAJob.WHITE_MONK, FFTAJob.BISHOP, FFTAJob.TEMPLAR},
			 new FFTACommand[] 	{FFTACommand.NONE, FFTACommand.ITEM, FFTACommand.BATTLE_TECH_B, FFTACommand.DRAGON_TECH, FFTACommand.DEFEND, FFTACommand.SPELLBLADE_TECH, FFTACommand.MONK_TECH, FFTACommand.PRAYER, FFTACommand.SACRED_TECH},
			 new FFTASupport[] 	{FFTASupport.NONE, FFTASupport.DOUBLEHAND, FFTASupport.HALF_MP, FFTASupport.MONKEYGRIP, FFTASupport.SHIELDBEARER, FFTASupport.WATK_PLUS, FFTASupport.WDEF_PLUS},
			 new FFTAReaction[] {FFTAReaction.NONE, FFTAReaction.BONECRUSHER, FFTAReaction.COUNTER, FFTAReaction.DRAGONHEART, FFTAReaction.LAST_BERSERK, FFTAReaction.REFLEX, FFTAReaction.RETURN_MAGIC, FFTAReaction.STRIKEBACK},
			 new FFTACombo[] 	{FFTACombo.NONE, FFTACombo.COMBAT_COMBO, FFTACombo.DRAGON_COMBO, FFTACombo.DEFEND_COMBO, FFTACombo.SWORD_COMBO, FFTACombo.MONK_COMBO, FFTACombo.PRAY_COMBO, FFTACombo.SACRED_COMBO}),
	
	HUMAN	("Human",
			 new FFTAJob[] 		{FFTAJob.SOLDIER, FFTAJob.PALADIN, FFTAJob.FIGHTER, FFTAJob.THIEF_H, FFTAJob.NINJA, FFTAJob.WHITE_MAGE_H, FFTAJob.BLACK_MAGE_H, FFTAJob.ILLUSIONIST_H, FFTAJob.BLUE_MAGE, FFTAJob.ARCHER_H, FFTAJob.HUNTER},
			 new FFTACommand[] 	{FFTACommand.NONE, FFTACommand.ITEM, FFTACommand.BATTLE_TECH_H, FFTACommand.CHIVALRY, FFTACommand.FIGHTER_TECH, FFTACommand.STEAL, FFTACommand.NINJA_SKILL, FFTACommand.WHITE_MAGIC, FFTACommand.BLACK_MAGIC, FFTACommand.PHANTASM_SKILL, FFTACommand.BLUE_MAGIC, FFTACommand.AIM, FFTACommand.HUNT},
			 new FFTASupport[] 	{FFTASupport.NONE, FFTASupport.CONCENTRATE, FFTASupport.DOUBLE_SWORD, FFTASupport.DOUBLEHAND, FFTASupport.GEOMANCY, FFTASupport.HALF_MP, FFTASupport.IMMUNITY, FFTASupport.LEARNING, FFTASupport.MAINTENANCE, FFTASupport.MONKEYGRIP, FFTASupport.SHIELDBEARER, FFTASupport.TURBO_MP, FFTASupport.WATK_PLUS, FFTASupport.WDEF_PLUS},
			 new FFTAReaction[] {FFTAReaction.NONE, FFTAReaction.ABSORB_MP, FFTAReaction.AUTO_REGEN, FFTAReaction.BLOCK_ARROWS, FFTAReaction.BONECRUSHER, FFTAReaction.COUNTER, FFTAReaction.DAMAGE_TO_MP, FFTAReaction.LAST_HASTE, FFTAReaction.REFLEX, FFTAReaction.RETURN_MAGIC, FFTAReaction.STRIKEBACK},
			 new FFTACombo[] 	{FFTACombo.NONE, FFTACombo.COMBAT_COMBO, FFTACombo.KNIGHT_COMBO, FFTACombo.FIGHT_COMBO, FFTACombo.THIEF_COMBO, FFTACombo.NINJA_COMBO, FFTACombo.WHITE_COMBO, FFTACombo.BLACK_COMBO, FFTACombo.SPELL_COMBO, FFTACombo.BLUE_COMBO, FFTACombo.BOW_COMBO, FFTACombo.HUNT_COMBO}),
	
	MOOGLE	("Moogle",
			 new FFTAJob[] 		{FFTAJob.THIEF_M, FFTAJob.JUGGLER, FFTAJob.GADGETEER, FFTAJob.ANIMIST, FFTAJob.MOG_KNIGHT, FFTAJob.GUNNER, FFTAJob.BLACK_MAGE_M, FFTAJob.TIME_MAGE_M},
			 new FFTACommand[] 	{FFTACommand.NONE, FFTACommand.ITEM, FFTACommand.CALL, FFTACommand.CHARGE, FFTACommand.GUNMANSHIP, FFTACommand.STEAL, FFTACommand.STUNT, FFTACommand.PANDORA, FFTACommand.BLACK_MAGIC, FFTACommand.TIME_MAGIC},
			 new FFTASupport[] 	{FFTASupport.NONE, FFTASupport.CONCENTRATE, FFTASupport.GEOMANCY, FFTASupport.MAINTENANCE, FFTASupport.SHIELDBEARER},
			 new FFTAReaction[] {FFTAReaction.NONE, FFTAReaction.AUTO_REGEN, FFTAReaction.BLOCK_ARROWS, FFTAReaction.CATCH, FFTAReaction.COUNTER, FFTAReaction.DAMAGE_TO_MP, FFTAReaction.LAST_HASTE, FFTAReaction.LAST_QUICKEN, FFTAReaction.RETURN_FIRE, FFTAReaction.RETURN_MAGIC},
			 new FFTACombo[] 	{FFTACombo.NONE, FFTACombo.ANIMAL_COMBO, FFTACombo.CHARGE_COMBO, FFTACombo.GUN_COMBO, FFTACombo.THIEF_COMBO, FFTACombo.JUGGLE_COMBO, FFTACombo.GADGET_COMBO, FFTACombo.BLACK_COMBO, FFTACombo.TIME_COMBO}),
	
	NU_MOU	("Nu Mou",
			 new FFTAJob[] 		{FFTAJob.WHITE_MAGE_N, FFTAJob.BLACK_MAGE_N, FFTAJob.TIME_MAGE_N, FFTAJob.ILLUSIONIST_N, FFTAJob.ALCHEMIST, FFTAJob.BEASTMASTER, FFTAJob.MORPHER, FFTAJob.SAGE},
			 new FFTACommand[] 	{FFTACommand.NONE, FFTACommand.ITEM, FFTACommand.WHITE_MAGIC, FFTACommand.BLACK_MAGIC, FFTACommand.TIME_MAGIC, FFTACommand.PHANTASM_SKILL, FFTACommand.ALCHEMY_SKILL, FFTACommand.CONTROL, FFTACommand.MORPH, FFTACommand.SAGACITY_SKILL},
			 new FFTASupport[] 	{FFTASupport.NONE, FFTASupport.GEOMANCY, FFTASupport.HALF_MP, FFTASupport.IMMUNITY, FFTASupport.MPOW_PLUS, FFTASupport.MAINTENANCE, FFTASupport.SHIELDBEARER, FFTASupport.TURBO_MP, FFTASupport.WDEF_PLUS},
			 new FFTAReaction[] {FFTAReaction.NONE, FFTAReaction.ABSORB_MP, FFTAReaction.DAMAGE_TO_MP, FFTAReaction.LAST_HASTE, FFTAReaction.LAST_QUICKEN, FFTAReaction.REFLEX, FFTAReaction.RETURN_MAGIC},
			 new FFTACombo[] 	{FFTACombo.NONE, FFTACombo.WHITE_COMBO, FFTACombo.BLACK_COMBO, FFTACombo.TIME_COMBO, FFTACombo.SPELL_COMBO, FFTACombo.GOLD_COMBO, FFTACombo.BEAST_COMBO, FFTACombo.MORPH_COMBO, FFTACombo.WISE_COMBO}),
	
	VIERA	("Viera",
			 new FFTAJob[] 		{FFTAJob.FENCER, FFTAJob.ELEMENTALIST, FFTAJob.RED_MAGE, FFTAJob.WHITE_MAGE_V, FFTAJob.SUMMONER, FFTAJob.ARCHER_V, FFTAJob.ASSASSIN, FFTAJob.SNIPER},
			 new FFTACommand[] 	{FFTACommand.NONE, FFTACommand.ITEM, FFTACommand.LUNGE_TECH, FFTACommand.SPIRIT_MAGIC, FFTACommand.RED_MAGIC, FFTACommand.WHITE_MAGIC, FFTACommand.SUMMON_MAGIC, FFTACommand.AIM, FFTACommand.CORNER, FFTACommand.SHARPSHOOT},
			 new FFTASupport[] 	{FFTASupport.NONE, FFTASupport.CONCENTRATE, FFTASupport.HALF_MP, FFTASupport.MPOW_PLUS, FFTASupport.SHIELDBEARER, FFTASupport.TURBO_MP},
			 new FFTAReaction[] {FFTAReaction.NONE, FFTAReaction.ABSORB_MP, FFTAReaction.AUTO_REGEN, FFTAReaction.BLOCK_ARROWS, FFTAReaction.CATCH, FFTAReaction.REFLEX, FFTAReaction.RETURN_FIRE},
			 new FFTACombo[] 	{FFTACombo.NONE, FFTACombo.LUNGE_COMBO, FFTACombo.SPIRIT_COMBO, FFTACombo.RED_COMBO, FFTACombo.WHITE_COMBO, FFTACombo.SUMMON_COMBO, FFTACombo.BOW_COMBO, FFTACombo.KILLER_COMBO, FFTACombo.SNIPER_COMBO}),
	
	DUMMY	("Dummy", null, null, null, null, null);

	
	
	public final String name;
	public final FFTAJob[] jobs;
	public final FFTACommand[] aAbilities;
	public final FFTASupport[] sAbilities;
	public final FFTAReaction[] rAbilities;
	public final FFTACombo[] cAbilities;
	
	FFTARace(String name, FFTAJob[] jobs, FFTACommand[] aAbs, FFTASupport[] sAbs, FFTAReaction[] rAbs, FFTACombo[] cAbs)
	{
		this.name = name;
		this.jobs = jobs;
		aAbilities = aAbs;
		sAbilities = sAbs;
		rAbilities = rAbs;
		cAbilities = cAbs;
	}
	
	public FFTAJob[] getJobs()
	{
		return jobs;
	}
	
	public String toString()
	{
		return name;
	}
}